application: sgbusesanalytics
version: 153
runtime: python
api_version: 1

handlers:

- url: /admin/clear_events
  script: main.py  
  login: admin  

- url: .*
  script: mobileanalytics/mobileanalytics.py
 
builtins:
- remote_api: on
